data:
  name: brats
  data_prep:
    use_lgg: true
    use_hgg: true
    use_data: ["T1", "T1CE", "T2", "FLAIR"]
    data_prep_option: "STACK"
    input_data: ["T1", "T1CE", "T2", "FLAIR"]
    output_data: ["T1", "T1CE", "T2", "FLAIR"]
  source_transforms:
    - name: centercrop3d
      args:
        size: [160, 192, 128]
  target_transforms:
    - name: centercrop3d
      args:
        size: [160, 192, 128]
model:
  name: "base"
  backbone: "nvidia2018"
  inr:
    name: weight_modulated_inr
    args:
      n_layer: 5
      hidden_dim: [256, 256, 256, 256]
      use_bias: true
      input_dim: 3
      output_dim: 12
      ff_sigma: 1024
      ff_dim: 120
      modulated_layers: [1]
      backbone_feature_dimensions: [-1, -1, -1, 7864320]
      modulated_layers_to_backbone_features_map:
        1: 4
      normalize_weights: True
trainer:
  epochs: 100
  batch_size: 2
  amp: false
  validation_frequency: 1.0
