data:
  name: brats
  data_prep:
    use_lgg: true
    use_hgg: true
    use_data: ["T1"]
    data_prep_option: "STACK"
    input_data: ["T1"]
    output_data: ["T1"]
    cluster_annotations: "channelwise"
  source_transforms:
    - name: centercrop3d
      args:
        size: [160, 192, 128]
  target_transforms:
    - name: centercrop3d
      args:
        size: [160, 192, 128]
model:
  name: "base"
  backbone:
    name: "nvidia2018"
    input_channels: 1
  latent_transform:
    name: convolutional
    levels:
      - n_layer: 1
        strides: [1]
        padding: ["same"]
        channels: [256]
        kernel_size: [1]
        backbone_idx: 4
        input_channels: 256
        batch_norm: true
  inr:
    name: weight_modulated_inr
    n_layer: 5
    hidden_dim: [256, 256, 256, 256] # needs to coincide with backbone embedding channels
    use_bias: true
    input_dim: 3
    output_dim: 1
    ff_sigma: 120
    ff_dim: 120
    normalize_weights: True
    modulated_layers: [1]
    backbone_spatial_feature_dimensions: [7680]
    modulated_layers_to_backbone_features_map:
      1: 0
  coord_sampler:
    coord_range: [-1.0, 1.0]
  subsampler:
    type: random
    ratio: 0.1
optimizer:
  type: adam
  init_lr: 0.0001
  weight_decay: 0.0001
  betas: [0.9, 0.999] #[0.9, 0.95]
  max_gn: null
hooks:
  - hook: tensorboard
    priority: 100
    cfg:
      directory: /home/simon/tum/mri-runs/debug
  - hook: lr_scheduler
    priority: 100
    cfg:
      scheduler_name: StepLR
      step_size: 1000
  - hook: visualization
    priority: 1
    cfg:
      directory: /home/simon/tum/mri-runs/debug
      frequency: 100
      num_slices: 8
  - hook: inr_metrics
    priority: 1
engine:
  epochs: 10000
  batch_size: 2
  amp: false
  validation_frequency: 1.0
